"""
The data shapes shared by the whole framework.
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

# The benchmark identifiers, defined once so every layer names
# them the same way.
BENCHMARK_MBPP = "mbpp"
BENCHMARK_SWEBENCH = "swebench"


class SandboxConfig(BaseModel):
    """Limits and permissions for the execution sandbox.

    Allowlist approach: only the imports in authorized_imports are
    allowed; everything else is blocked by default. Loaded from a JSON
    config file.
    """
    authorized_imports: List[str] = Field(default_factory=lambda: [
        "math", "math.*",
        "collections", "collections.*",
        "itertools", "re", "json",
        "typing", "typing.*",
        "functools", "operator",
        "heapq", "bisect", "copy",
        "string", "random",
        "datetime", "datetime.*",
        "array", "cmath",
    ])
    allowed_directories: List[str] = Field(default_factory=lambda: [
        "/testbed", "/tmp/agent"
    ])
    max_execution_time_seconds: int = 30
    max_memory_mb: int = 512


class MBPPTaskInput(BaseModel):
    """An MBPP task, loaded from the dumped task.json."""
    task_id: int
    task_definition: str
    function_definition: str
    test_imports: List[str] = Field(default_factory=list)
    test_list: List[str] = Field(default_factory=list)


class SWEBenchTaskInput(BaseModel):
    """A SWE-bench task, loaded from the dumped task.json.

    The run ends with a git patch for the repo inside the task's
    Docker image.
    """
    instance_id: str = Field(
        ...,
        description=(
            "SWE-bench instance identifier (e.g., 'sympy__sympy-23534')"
        ),
    )
    problem_statement: str = Field(
        ...,
        description="The GitHub issue description, what needs to be fixed",
    )
    docker_image: str = Field(
        ...,
        description=(
            "Full Docker image name to pull (e.g., 'swebench/"
            "sweb.eval.x86_64.sympy_1776_sympy-23534:latest')"
        ),
    )
    eval_script: str = Field(
        ...,
        description=(
            "Bash script to run inside the container to evaluate the patch"
        ),
    )
    hints_text: str = Field(
        default="",
        description="Optional hints about the issue (may be empty)",
    )
    repo: str = Field(
        default="",
        description="Repository name (e.g., 'sympy/sympy')",
    )


class StepMetrics(BaseModel):
    """Metrics for a single agent step.

    Each step corresponds to one LLM generate -> sandbox execute cycle.
    All fields are required, empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """
    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(
        ..., description="Tokens sent to the LLM for this step"
    )
    output_tokens: int = Field(
        ..., description="Tokens generated by the LLM for this step"
    )
    request_time_ms: float = Field(
        ...,
        description="Wall-clock time for the LLM API call in milliseconds",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp of when this step was recorded",
    )
    api_url: str = Field(
        default="",
        description=(
            "Base URL of the LLM API endpoint "
            "(e.g., 'https://openrouter.ai/api/v1')"
        ),
    )
    model_name: str = Field(
        default="",
        description=(
            "Model identifier used for this step "
            "(e.g., 'qwen/qwen3-235b-a22b-2507')"
        ),
    )
    llm_output: str = Field(
        default="",
        description="Raw text generated by the LLM before code extraction",
    )
    sandbox_input: str = Field(
        default="",
        description="Python code sent to the sandbox for execution",
    )
    sandbox_output: str = Field(
        default="",
        description="Sandbox execution result (stdout/stderr/error message)",
    )
    retries: int = Field(
        default=0,
        description=(
            "Number of LLM API retries before getting a successful "
            "response (0 = first attempt succeeded)"
        ),
    )


class SolutionOutput(BaseModel):
    """The final result of a run, written to solution.json.

    Built from the step trace at the end of every run, including
    failed ones, where error is set and success is False.
    """
    task_id: str = Field(
        ...,
        description=(
            "Task identifier (MBPP task_id as string, "
            "or SWE-bench instance_id)"
        ),
    )
    benchmark: str = Field(
        ..., description="Benchmark type: 'mbpp' or 'swebench'"
    )
    success: bool = Field(
        ..., description="Whether the agent believes it solved the task"
    )
    solution: str = Field(
        ...,
        description=(
            "For MBPP: the Python function code. "
            "For SWE-bench: the git patch (diff)"
        ),
    )
    iterations: int = Field(
        ..., description="Number of agent loop iterations used"
    )
    total_requests: int = Field(
        ...,
        description=(
            "Total number of LLM API requests made (including retries)"
        ),
    )
    total_input_tokens: int = Field(
        ..., description="Sum of input_tokens across all steps"
    )
    total_output_tokens: int = Field(
        ..., description="Sum of output_tokens across all steps"
    )
    total_time_seconds: float = Field(
        ..., description="Wall-clock time from agent start to finish"
    )
    steps: List[StepMetrics] = Field(
        default_factory=list,
        description="Per-step metrics, one entry per agent iteration",
    )
    system_prompt: str = Field(
        default="",
        description=(
            "Full system prompt sent to the LLM (for provenance checking)"
        ),
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if the agent failed (None if successful)",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp of when the solution was produced",
    )

    @classmethod
    def from_steps(
        cls,
        task_id: str,
        benchmark: str,
        success: bool,
        solution: str,
        steps: List[StepMetrics],
        total_time_seconds: float,
        system_prompt: str = "",
        error: Optional[str] = None,
    ) -> "SolutionOutput":
        """Build the output from the steps, computing all the totals."""
        return cls(
            task_id=task_id,
            benchmark=benchmark,
            success=success,
            solution=solution,
            iterations=len(steps),
            total_requests=sum(1 + s.retries for s in steps),
            total_input_tokens=sum(s.input_tokens for s in steps),
            total_output_tokens=sum(s.output_tokens for s in steps),
            total_time_seconds=total_time_seconds,
            steps=steps,
            system_prompt=system_prompt,
            error=error,
        )
