"""
Extracts the Python code to execute from an LLM reply.

The primary format is the ```python fenced block; several blocks in one
reply are joined in order, and a final block left unclosed (the reply
was cut by a token limit or stop sequence) is still recovered. Tool
calls in other formats (Anthropic XML, Hermes JSON, ReAct) are converted
to the equivalent Python call, so the sandbox only ever sees Python.
"""

import json
import re

# Compiled once at import and used on every model response.
# Optional language tag: weak models forget it.
# Non-greedy: close at the first ```, not the last.
# DOTALL: code spans lines.
_PYTHON_BLOCK = re.compile(r"```(?:python|py)?\n(.*?)```", re.DOTALL)

# Detects an unclosed block.
_OPEN_FENCE = re.compile(r"```(?:python|py)?\n")

# Anthropic-style tool calls. [^"] stops at the closing quote.
_XML_INVOKE = re.compile(r'<invoke name="([^"]+)">(.*?)</invoke>', re.DOTALL)
_XML_PARAM = re.compile(
    r'<parameter name="([^"]+)">(.*?)</parameter>', re.DOTALL
)

# ReAct format. Locates where the JSON starts
# payload goes to _DECODER.
_REACT_CALL = re.compile(r"Action:\s*(\w+)\s*Action Input:")

# raw_decode(): reads one JSON value from an offset, ignores the rest.
_DECODER = json.JSONDecoder()


def extract(text: str) -> str | None:
    """
    Return the Python code found in an LLM reply.

    Tool calls in other formats (XML, JSON, ReAct) are converted to the
    equivalent Python call, so the sandbox only ever sees Python code.

    Args:
        text: Raw text generated by the LLM.

    Returns:
        The Python code to execute, or None when no code was found.
    """
    for parse in (_python_blocks, _xml_call, _json_call, _react_call):
        code = parse(text)
        if code:
            return code
    return None


def was_recovered(text: str) -> bool:
    """
    Report whether the reply ended on a block that was never closed.

    Args:
        text: Raw text generated by the LLM.

    Returns:
        True when the code had to be read to the end of the reply.
    """
    end = 0
    for match in _PYTHON_BLOCK.finditer(text):
        end = match.end()
    return bool(_OPEN_FENCE.search(text, end))


def _python_blocks(text: str) -> str | None:
    """Join all ```python blocks, in order."""
    blocks = []
    end = 0
    for match in _PYTHON_BLOCK.finditer(text):
        blocks.append(match.group(1))
        end = match.end()
    # an opening fence never closed means the reply was cut mid-block:
    # recover what is there instead of wasting an iteration
    tail = _OPEN_FENCE.search(text, end)
    if tail:
        blocks.append(text[tail.end():])
    if not blocks:
        return None
    return "\n".join(block.strip() for block in blocks)


def _xml_call(text: str) -> str | None:
    """Convert an Anthropic-style <invoke> call to a Python call."""
    match = _XML_INVOKE.search(text)
    if not match:
        return None
    name, body = match.groups()
    # XML carries no types, so every parameter is passed as a string
    params = {key: value.strip() for key, value in _XML_PARAM.findall(body)}
    return _as_code(name, params)


def _json_call(text: str) -> str | None:
    """Convert a Hermes-style <tool_call> JSON call to a Python call."""
    start = text.find("<tool_call>")
    if start == -1:
        return None
    call = _decode_json(text, start)
    if call is None:
        return None
    return _as_code(call.get("name"), call.get("arguments", {}))


def _react_call(text: str) -> str | None:
    """Convert a ReAct Action / Action Input pair to a Python call."""
    match = _REACT_CALL.search(text)
    if not match:
        return None
    args = _decode_json(text, match.end())
    if args is None:
        return None
    return _as_code(match.group(1), args)


def _decode_json(text: str, start: int) -> dict | None:
    """Parse one complete JSON object found at or after start."""
    brace = text.find("{", start)
    if brace == -1:
        return None
    # raw_decode reads exactly one JSON value, so nested braces and
    # braces inside strings are handled correctly
    try:
        value, _ = _DECODER.raw_decode(text, brace)
    except json.JSONDecodeError:
        return None
    return value if isinstance(value, dict) else None


def _as_code(name: str | None, arguments: dict) -> str | None:
    """Render a tool name and its arguments as Python source."""
    if not name:
        return None
    # repr() turns JSON values (True, None, "x") into Python literals
    args = ", ".join(f"{key}={value!r}" for key, value in arguments.items())
    return f"{name}({args})"
